# deployment on separate namespace
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy2-loginapp
  namespace: loginapp
spec:
  selector:
    matchLabels:
      app: deploy2-loginapp
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: deploy2-loginapp
    spec:
      containers:
      - name: deploy2-loginapp
        image: satyasandeep901/myloginimage31jul22:2
        resources:
          requests:
              memory: 512Mi
              cpu: 0.5

---
apiVersion: v1
kind: Service
metadata:
  name: deploy2-loginapp-svc
  namespace: loginapp

spec:

  selector:
    app: deploy2-loginapp

  ports:
    - name: http
      port: 8080

  type: ClusterIP